# PostgreSQL Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5440/habit_app_db
spring.datasource.username=postgres
spring.datasource.password=A1&G2&Dk3_P4**FirstApp

# JPA ve Hibernate Ayarlar? (Tablolar? otomatik olu?turmas? için)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Secret Key (Base64/Hex format?nda güvenli bir anahtar)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970